### ISSUE TITLE
[Bug]: "Cannot find function map on type Link" in Blocking view

### ISSUE THREAD

**Issue by prayidae** [callumalpass/tasknotes#1304]
### Bug Description

Obsidian has started throwing a repeated error on every task note where the Relationships base is embedded: `Failed to evaluate a filter: cannot find function "map" on type Link`.

The error notification pops up every time I make a change to the active file, if that file has an embedded Relationships base, and the Blocking view is open in the base. So I infer it is complaining about this filter on the Blocking view: `note.blockedBy.map(value.uid).contains(this.file.asLink())`.

**Additional context**
I don't use the Relationships widget, instead I manually embed the Relationships base.

**Comment by callumalpass** [comment]
Thanks @prayidae. This should be fixed in 4.2.0. You may have to update the bases files.

**Comment by prayidae** [comment]
Thank you for working on this! 

I just manually replaced the `note.blockedBy.map(value.uid).contains(this.file.asLink())` filter with the new version in the current TaskNotes documentation: `list(note.blockedBy).map(value.uid).contains(this.file.asLink())`. 

Unfortunately now it is throwing a new error: `Failed to evaluate a filter: cannot find "uid" on type Link`. 

I am reluctant to replace the entire Relationships base with the new default version as I've made various customizations to it that I would prefer not to have to replicate individually--but that may be necessary, if this is expected behavior because of the changes to the UID behavior from recent updates? But wanted to report the error in case it is not expected behavior.

**Comment by prayidae** [comment]
I tried deleting and recreating the Relationships base and the error is still being thrown so created a new issue #1439
