### ISSUE TITLE
[FR]: Make date entry fields behave consistently

### ISSUE THREAD

**Issue by kazerniel** [callumalpass/tasknotes#1392]
### Feature Description

Currently if I just continuously type a YYYYMMDD date in the field, like I would in an Obsidian date property, it ends up with the first 6 digits going into the year field, which messes up the rest of the date.

Conversely if I try to press tab after filling each field, it jumps from year to month correctly, but since month only allows two digits, if I press tab after filling it, it was already in the day field, so it loops around to select the calendar open button at the beginning of the field.

So currently I'm supposed to write in the year, press tab, write in the month, remember **not** to press tab, then write in the day. I feel like this is not a user-friendly UI design. Capping the year field at 4 digits, like Obsidian does, would solve it.

(Additional bug I've just come across: these date fields don't allow pasting dates.)

**Comment by callumalpass** [comment]
Thanks for reporting this @kazerniel. I'll have a look into it.

**Comment by callumalpass** [comment]
Thank you for reporting this. This should be resolved in release 4.8.0, so I am going to close this issue now.

**Comment by kazerniel** [comment]
@callumalpass Hello, I just updated to v4.9.1 and this issue is still present in the date entry fields.

**Comment by callumalpass** [comment]
Resolved in 4.9.2. Thanks, @kazerniel. I’m closing this issue.
