### ISSUE TITLE
Issues with dates and calendar

### ISSUE THREAD

**Issue by coneos** [callumalpass/tasknotes#16]
Great plugin but task due dates do not seem to work properly
When I set a due date to today it sets the due date to yesterday so i have to set a task due date to tomorrow to have it due for today, I already tried different date formats but still the same.
Also in calendar i do see there are tasks for these dates but clicking the dates do not display the tasks

**Comment by callumalpass** [comment]
Could you please confirm which version you're having this problem with? It was certainly a problem in version 2.0.x, but I believe in 2.1.0 it should be fixed. 

In any case, I'll work on making the time zone parsing more robust--if the problem is persisting in 2.1.0, this will be the cause.  

When you click on a date in the calendar, it should bring the **Agenda view** and the **Notes View** to the date you've selected. It won't open any task lists. I'll have a think about making this more intuitive though.

**Comment by coneos** [comment]
OK now I understand that the calendar view allows to filter the agenda view. 
The issue still persists with version 2.10. When I set the due date or scheduled date to today (June 9) it sets it to June 8 in the agenda that is probably why the Test due today appears when I click on June 8 or June 9 see capture below ![Image](https://github.com/user-attachments/assets/5906fb09-e439-46d4-b32d-58ea1d5e5c46)
I am located in Mexico GMT-6, let me know how can I help debug this thanks!

**Comment by callumalpass** [comment]
Thanks, that's helpful to know. I'll be working on a release in the next few hours which I hope will address this.

**Comment by callumalpass** [comment]
I believe this is resolved in the latest release. Please let me know if the problem persists for you!
