### ISSUE TITLE
[Bug]: Can not close task edit modal on mobile

### ISSUE THREAD

**Issue by anareaty** [callumalpass/tasknotes#404]
### What's the bug?

When I open task edit modal on Android and then try to close it by tapping the "x" button in the corner, nothing happens and modal does not close. If I tap on "Cancel" button instead, modal closes normally.

It also seems like the "x" button does not get touched at all, because there is no visual indication that it was tapped. Probably there is something that prevents it from reseiving the touch event, but I tried it with the default theme and with other plugins turned off, and it doesn't help. On desktop the button works as intended.

### What did you expect to happen?

Modal should close when the "x" button is pressed.

### Which part of TaskNotes is affected?

None

### Technical Details (Optional)

SYSTEM INFO:
	Operating system: android 15 (Xiaomi 23030RAC7Y)
	Webview version: 138.0.7204.179
	Obsidian version: 1.9.7 (229)
	API version: v1.9.7
	Login status: not logged in
	Language: ru
	Live preview: on
	Base theme: light
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 22
	Plugins enabled: 1
		1: TaskNotes v3.19.1

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by callumalpass** [comment]
Thanks for reporting this @anareaty . This should be fixed in 3.20.0

**Comment by anareaty** [comment]
Hi! Unfortunately the update did not fix the issue for me, but I figured out where the bug is coming from. It seems to be that the button is covered up by the title element. After I added the css snippet ".modal-close-button {z-index: 99;}" it started to work as expected.

**Comment by callumalpass** [comment]
I think this was an Obsidian issue. Should be fixed with Obsidian release 1.10.0
