### ISSUE TITLE
[Bug]: contexts parsing not recognising non-english context name

### ISSUE THREAD

**Issue by Arachnidai** [callumalpass/tasknotes#485]
### What's the bug?

When I create a new task using the "create new task" command, I am unable to set the context to a language other than English (specifically, Cyrillic). The parser does not recognize @context_name (for example, let's say it's `ознакомиться`) as a context.

![Image](https://github.com/user-attachments/assets/a2ff866d-90c7-49da-8d11-d297b4fafbe7)
![Image](https://github.com/user-attachments/assets/ad0e1a75-b826-48a2-ab6c-e08a304caa2e)

However, manual filling works when the detailed options are expanded.

### Which part of TaskNotes is affected?

Other

**Comment by callumalpass** [comment]
Thanks @Arachnidai . I'll look for a fix for this.

**Comment by callumalpass** [comment]
This should be resolved in the latest release. You can now set your own custom trigger for each NLP property. You should add the '@' symbol that you use as the context trigger.

**Comment by Arachnidai** [comment]
Unfortunately, it still does not work as it should. 
Plugin version 4.0.4. 


Here are the upholstery steps more explicitly:

Creation of task:

<img width="585" height="387" alt="Image" src="https://github.com/user-attachments/assets/1dc581b9-789e-4f4c-b9e6-52e2f748432f" />

Context 1 is in English, it was recognized.
Context 2 is in Cyrillic, it was not **not** recognized.

As a result, context from modal was recognized as this:


<img width="579" height="930" alt="Image" src="https://github.com/user-attachments/assets/5829258b-bedb-4295-8bb1-1222bdae678e" />


and the created note will look like this:

<img width="1391" height="766" alt="Image" src="https://github.com/user-attachments/assets/26ceb0d3-0a25-4096-8946-2c264010aae3" />


Autocompletion sees the text in Cyrillic and offers to supplement it:

![Image](https://github.com/user-attachments/assets/394c5040-ca4e-4ae1-9df7-dea32e0d85af)


But replacing the title of the note and transferring it to the context does not work.

For work with this, I need to manually open the modal window and write the context directly in the field.

**Comment by callumalpass** [comment]
Sorry, @Arachnidai . Just to confirm--have you added the Cyrillic '@' to the NLP triggers? (Settings > Features > NLP Triggers)

**Comment by Arachnidai** [comment]
The trigger symbol I have is standard:

<img width="781" height="434" alt="Image" src="https://github.com/user-attachments/assets/862764a6-f52a-4d47-8177-fdc9d856ff44" />

Changing the trigger to another one does not change the outcome.

And what do you mean by a Cyrillic `@`?

**Comment by callumalpass** [comment]
I think I misunderstood the problem, @Arachnidai , apologies. This will be fixed in the next release.

**Comment by Arachnidai** [comment]
Happens to everyone. Thank you for your attention to this issue, @callumalpass

**Comment by callumalpass** [comment]
This should be fixed in 4.1.0
