### ISSUE TITLE
[Bug]: Status order in Kanban and Bases Kanban views breaks

### ISSUE THREAD

**Issue by berzernberg** [callumalpass/tasknotes#615]
### What's the bug?

1. Configure custom status names and properties
2. Create Kanban View in any Base
3. Order of statuses (columns) is incorrect and chaotic
4. You can't change this order in Bases

Additionaly, in Kanban view, my preconfigured columns order (via drag and drop fucntion) breaks when I (or system) accidentally sets incorrect status in status property. For example, if you set status "open" instead of "Open", it creates an additional column for this status, and the whole order of columns breaks. 

Also, TaskNotes doesn't understand status correctly if this status set in "list" manner, instead of text. For example:
status:
- "Open"
instead of
status: Open

If so, it also creates new column and breaks the order.

### What did you expect to happen?

Expected to have an order, configured in settings. None, Open, In progres, Done, Review. 
If any new status added, it should appear the last, after all existing statuses without breaking the order.

### Which part of TaskNotes is affected?

Kanban Board

**Comment by glpayson** [comment]
In case it helps, here is a gif of the Bases + TaskNotes Kanban columns not moving when you try to drag them. 

![Image](https://github.com/user-attachments/assets/92329ffb-4e71-41a5-917e-171f50b6a475)

- OS: macOS Sequoia 15.5
- Obsidian: v1.9.12
- Installer version: v1.8.10
- TaskNotes: v3.23.1

**Comment by callumalpass** [comment]
Thanks for raising this @berzernberg, and for the gif, @glpayson  . I'll work on it! There's still a lot of kinks in the Bases integration--some of these will likely not be solved until the Bases API is made official.

Please not that if this is fixed before the release of the Bases API, it will likely only be a partial fix; the Board order will not persist after closing and reopening Obsidian. Hopefully the Bases API will allow grouping and for the recording of the order of groups *in the Bases metadata*. That will enable persistent board order.

**Comment by berzernberg** [comment]
@callumalpass Thank you! But what about order in TaskNotes Kanban view? In my case, it almost always resets and messes the order of colums. I can change it, it will be saved. But when I create new view, I have to manually adjust the order, even though it always set for status grouping. And if any task accidentally have inproper status (open instead of Open, or something like this), then columns order messes up in every view again.

It will be great if
1. Order persisted even if new columns are added (let them appear last in order)
2. Default order of columns for statuses follows the status order in settings

**Comment by callumalpass** [comment]
@berzernberg , what version are you using? That behaviour should be fixed in 3.24.2

**Comment by berzernberg** [comment]
> [@berzernberg](https://github.com/berzernberg) , what version are you using? That behaviour should be fixed in 3.24.2

I am using 3.23.4, as any other new version shows empty tabs, agendas, calendars. Noticed this yesterday, today updated to a latest version, and the issue remains. Sorry for inconvinience, didn't knew your newer versions fixed this. But I have this empty tabs issue.

**Comment by callumalpass** [comment]
I'm sorry to hear that you've encountered those issues @berzernberg . I'll push a release for that in the next couple of hours.

**Comment by callumalpass** [comment]
@berzernberg , release 3.24.3 should fix the blank screen issue. You should be able to upgrade now. I'd be curious to know what you think about the Kanban fixes from 3.24.0. Just a heads up--the fixes are only for TaskNotes native Kanban view, not for the Bases Kanban view.

**Comment by callumalpass** [comment]
Closing as completed. The Kanban bases view supports column ordering in v4.
