### ISSUE TITLE
[Bug]: Display names for formulas are not applied in a Task List View base

### ISSUE THREAD

**Issue by JoelJansenD** [callumalpass/tasknotes#624]
### What's the bug?

1. I created a task for today
2. I created the following base:

```base
formulas:
  formattedDate: date(scheduled).format("DD MMMM YYYY")
properties:
  file.name:
    displayName: Taak
  formula.formattedDate:
    displayName: Gepland op
views:
  - type: tasknotesTaskList
    name: Tasks
    filters:
      and:
        - date(scheduled) == date(this.file.properties.today)
    order:
      - file.name
      - formula.formattedDate
    sort:
      - property: scheduled
        direction: ASC
    columnSize:
      file.name: 504

```

3. The display name is not applied (see screenshot below)

### What did you expect to happen?

I would expect the given display name to appear, rather than the formula name. This exact same configuration works in the default Obsdian Base.

### Which part of TaskNotes is affected?

Task List View

### Screenshots or Screen Recordings

<img width="908" height="264" alt="Image" src="https://github.com/user-attachments/assets/38868557-fc2d-489f-a82e-954007fe2360" />

### Technical Details (Optional)

SYSTEM INFO:
	Obsidian version: v1.9.12
	Installer version: v1.4.14
	Operating system: Windows 10 Pro 10.0.19045
	Login status: logged in
	Language: en-GB
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: TaskNotes v3.23.1

**Comment by benoitjadinon** [comment]
formulas as properties don't work in the new Calendar Base View either

**Comment by callumalpass** [comment]
This should be fixed in v4

**Comment by benoitjadinon** [comment]
<img width="1616" height="692" alt="Image" src="https://github.com/user-attachments/assets/45096098-efa0-4aef-80c8-61c84bd67525" />
@callumalpass can we reopen this please ? I'm running 4.3.3

**Comment by Sirnii** [comment]
I ran into what looks like a second bug in the same rendering path, and I think it helps explain why this issue is still showing up in newer versions.

In my case, `tasknotesTaskList` was not only ignoring the configured Bases display names, it was also rendering some date-like values as the raw Lucide icon token `clock`.

What it looked like in the card metadata:
- `lastTouched: clock`
- `modified-c: clock`

What I expected:
- `Last touched: 13 days ago`
- `Modified c: Mar 2` (or whatever Bases normally displays)

A few details that make me think this belongs in the same rendering path as this issue:

1. Native Obsidian Base table rendering showed the same formula/property values correctly, so Bases evaluation itself seemed fine.
2. In the TaskNotes source, `getBasesVisibleProperties()` is already able to read the Bases display name from the query props map:
   - `src/bases/helpers.ts` around `308-315`
3. But `renderGenericProperty()` in `src/ui/TaskCard.ts` still derives the label from the raw property id instead of using that display name:
   - `src/ui/TaskCard.ts` around `1169-1178`
4. Separately, `extractBasesValue()` in `src/ui/TaskCard.ts` prefers `data` before `display` / `date` for non-link Bases value objects:
   - `src/ui/TaskCard.ts` around `575-585`

That seems important because for some Bases values, `data` appears to hold the icon token while the human-readable value lives in `display` or `date`. In practice, that is what produced `clock` for me.

I tested a local patch in the built plugin and it fixed both symptoms at once:

- In `extractBasesValue()`, for non-link Bases value objects, prefer:
  - `display`
  - then `date`
  - then raw `data`
- Also don't restrict the date fallback to `lucide-calendar` only; date-like values can apparently come through with other icons such as `lucide-clock`.
- For labels, either pass the Bases display name through to the task-card renderer, or let `renderGenericProperty()` ask the Bases config/adapter for `getDisplayName(propertyId)` instead of reconstructing the label from `propertyId`.

After making those changes locally, both formula-based relative dates like `file.mtime.relative()` and non-formula date-like properties such as `modified-c` rendered correctly in the same `tasknotesTaskList` view.

So my guess is:
- this issue is not only “display names for formulas are not applied”
- it is more generally a Task Card / Bases metadata rendering mismatch, where the renderer is using the wrong field from Bases value objects and also not using the display names already available from Bases

Observed on TaskNotes `4.4.0`.
