### ISSUE TITLE
[Bug]: Imported full-day-events show up twice in agenda view

### ISSUE THREAD

**Issue by realJohnDoe** [callumalpass/tasknotes#695]
### What's the bug?

First of all, thanks for developing this plugin! I had a similar idea of managing tasks, notes, events and potentially also messages as markdown files for some months and this implementation comes pretty close. 🥳

So I am testing the plugin for everyday use since a few days now and noticed that full-day events from my Proton calendar show up both on the correct day as well as on the day after, in Agenda view. Non-full-day events show up at the correct time. Curiously, in the advanced calendar view, full-day events correctly show up only once. 

This happens on both the Android client and on the desktop client on Windows 11.

If I can somehow support in debugging or fixing this, please let me know how - I have quite some developer experience, but none with Obsidian plugins yet.

### What did you expect to happen?

That full day events show only once on the correct day in Agenda view.

### Which part of TaskNotes is affected?

Agenda View

**Comment by callumalpass** [comment]
Hi @realJohnDoe . Thanks for reporting this. This sounds like it is potentially a timezone issue. Would you feel comfortable sharing a minimal ICS file that reproduces the problem that you're seeing?

**Comment by realJohnDoe** [comment]
@callumalpass Thanks for picking this up.
Here is a minimal ics file I exported from Proton Calendar that I can use to reproduce the bug. For reference, I am on CET timezone with daylight saving time on all my systems.

```ics
BEGIN:VCALENDAR
PRODID:-//Proton AG//ProtonCalendar 1.0.0//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:Test Full day event
X-WR-CALDESC:
X-WR-TIMEZONE:Europe/Berlin
REFRESH-INTERVAL;VALUE=DURATION:PT240M
X-PUBLISHED-TTL:PT240M
BEGIN:VTIMEZONE
TZID:Europe/Berlin
LAST-MODIFIED:20250218T131521Z
X-LIC-LOCATION:Europe/Berlin
BEGIN:DAYLIGHT
TZNAME:CEST
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZNAME:CET
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
END:VCALENDAR
```

**Comment by callumalpass** [comment]
Thanks for that, @realJohnDoe  This will be fixed in the next release.

**Comment by callumalpass** [comment]
Fixed in 3.24.0

**Comment by realJohnDoe** [comment]
@callumalpass I am sorry to say but it seems like the bug is back since the latest release 😕
