### ISSUE TITLE
[Bug]: Recurring daily task completed when clicked

### ISSUE THREAD

**Issue by edakimling** [callumalpass/tasknotes#936]
### Bug Description

It appears the logic is that if you have a daily recurring task, as an example, and you click it completed on the status, it gets striked out and faded. When next day rolls, it appears same task will be changed in status for this new day.

This logic works fine but fails to take into account that a task could be overdue.
For instance, if a day old daily recurring task is clicked, it should not stay faded and status changed to completed, but rather it should remain status todo and changed to today's date...
Caveat: what to do if the date clicked on was 2 days ago...should the date upon clicking completed be changed to yesterday...and keep happening till we reach today's date?

**Comment by chrabia** [comment]
That would be very helpful.
When it comes to the caveat: it could be done the same way as in Obsidian Tasks plugin:
https://publish.obsidian.md/tasks/Getting+Started/Recurring+Tasks#Repeating+a+Task+Based+on+the+Original+Due+Date+or+the+Completion+Date

**Comment by callumalpass** [comment]
Thanks @edakimling, and thanks @chrabia for the Tasks reference. This appears resolved in current TaskNotes. For scheduled-anchor recurring tasks, completing a late task without an explicit view date records the scheduled occurrence, so a daily task scheduled for yesterday advances to today rather than marking today complete and skipping it. TaskNotes also supports recurrence_anchor: completion for the alternative repeat-from-completion-date workflow

**Comment by chrabia** [comment]
this still doesn't seem to be working right. For a daily task scheduled yesterday, when clicked, the scheduled date jumps to tomorrow.
